//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string age { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public string Comment1 { get; set; }
        public Nullable<System.DateTime> DateComment { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsAllow { get; set; }
        public string AllowUser { get; set; }
        public Nullable<System.DateTime> DateAllow { get; set; }
        public string Image { get; set; }
    }
}
