//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductId { get; set; }
        public string TenGoi { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<long> ProductGroupID { get; set; }
        public string Image { get; set; }
        public string Des { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<long> CountView { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string CategoryName { get; set; }
        public string ProductGroupName { get; set; }
        public string ImageList { get; set; }
        public string CuPhap { get; set; }
        public string DauSo { get; set; }
        public string LuuLuong { get; set; }
    }
}
