//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public long Id { get; set; }
        public System.DateTime Schdate { get; set; }
        public Nullable<int> TeamMemId { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    }
}
